import os
from typing import Dict, Any, List

class ExplainabilityEngine:
    """
    Provides transparency and explainability for predictions generated by the platform.
    Decomposes Churn Risk into exact contributing drivers and percentages.
    """
    
    @staticmethod
    def explain_churn_risk(record: Dict[str, Any]) -> Dict[str, Any]:
        """
        Deconstructs the Churn Risk prediction for a customer feedback record.
        Formula factors:
          - Rating: 1=+60%, 2=+45%, 3=+20%, 4=+5%
          - Category: App Bug/Billing=+15%, Staff/Support=+8%, others=0%
          - Sentiment: Negative=+15%, Neutral=0%, Positive=0%
          - Base: +5% default
        """
        # Read fields
        rating = record.get("rating")
        category = record.get("category", "Other")
        sentiment = record.get("sentiment", "Neutral")
        churn_risk = record.get("churn_risk_percent", 5)
        
        # Calculate individual points contribution
        contribs = []
        
        # 1. Rating contribution
        rating_pts = 0
        if rating is not None:
            rat_int = int(rating)
            if rat_int == 1:
                rating_pts = 60
            elif rat_int == 2:
                rating_pts = 45
            elif rat_int == 3:
                rating_pts = 20
            elif rat_int == 4:
                rating_pts = 5
                
        if rating_pts > 0:
            contribs.append(("Low Customer Rating", rating_pts))
            
        # 2. Category contribution
        cat_pts = 0
        if category in ["App Bug", "Billing"]:
            cat_pts = 15
        elif category == "Staff/Support":
            cat_pts = 8
            
        if cat_pts > 0:
            contribs.append((f"Operational issue in '{category}'", cat_pts))
            
        # 3. Sentiment contribution
        sent_pts = 0
        if sentiment == "Negative":
            sent_pts = 15
            
        if sent_pts > 0:
            contribs.append(("Negative Sentiment Tone", sent_pts))
            
        # 4. Base baseline
        base_pts = 5
        contribs.append(("Base Customer Loyalty Factor", base_pts))
        
        total_pts = sum(pts for _, pts in contribs)
        
        # Format contributing factors as percentages
        factors = []
        for name, pts in contribs:
            pct = round((pts / total_pts) * 100.0, 1)
            factors.append({
                "factor": name,
                "percentage": pct,
                "points": pts
            })
            
        # Sort factors by percentage descending
        factors = sorted(factors, key=lambda x: x["percentage"], reverse=True)
        
        # Determine drivers
        primary_driver = factors[0]["factor"] if len(factors) > 0 else "Base Baseline"
        primary_pct = factors[0]["percentage"] if len(factors) > 0 else 100.0
        
        secondary_driver = factors[1]["factor"] if len(factors) > 1 else "None"
        secondary_pct = factors[1]["percentage"] if len(factors) > 1 else 0.0
        
        # Determine confidence score based on ratings and data presence
        # If both rating and text are present, confidence is high. If only text, medium.
        if rating is not None and record.get("feedback_text"):
            confidence_score = 92.0
        elif rating is not None:
            confidence_score = 80.0
        else:
            confidence_score = 70.0
            
        # Determine business impact contribution
        impact_score = record.get("business_impact_score", 15)
        if impact_score >= 80:
            impact_contrib = "Critical"
        elif impact_score >= 60:
            impact_contrib = "High"
        elif impact_score >= 35:
            impact_contrib = "Medium"
        else:
            impact_contrib = "Low"
            
        # Build explanation description
        reason = f"Churn risk is driven primarily by {primary_driver.lower()} ({primary_pct}%)"
        if secondary_driver != "None":
            reason += f", compounded by {secondary_driver.lower()} ({secondary_pct}%)"
        reason += "."
        
        return {
            "prediction": f"{churn_risk}% Churn Risk",
            "confidence_score": confidence_score,
            "reason": reason,
            "primary_driver": f"{primary_driver} ({primary_pct}%)",
            "secondary_driver": f"{secondary_driver} ({secondary_pct}%)" if secondary_driver != "None" else "N/A",
            "contributing_factors": factors,
            "business_impact_contribution": impact_contrib
        }
